Repository kuzzleio/kuzzle-plugin-cluster, pull requests merged in 2018-06, with the labels that each got.

#55 dev stack - fix empty nginx upstream
  docker-compose/nginx/tpl/kuzzle.conf.tpl
  package.json
Labels: changelog:bug-fixes

#54 add a standalone compose stack
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  dev-npm-install.sh
  dev.sh
  docker-compose.yml
  docker-compose/config/kuzzlerc.dev
  docker-compose/config/kuzzlerc.prod
  docker-compose/docker-compose.yml.tpl
  docker-compose/images/kuzzle/Dockerfile
  docker-compose/npm-install.yml.tpl
  package.json
Labels: changelog:enhancements

#56 Add hooks for admin controller
  .github/issue_template.md
  .github/pull_request_template.md
  docker-compose/config/kuzzlerc.dev
  docker-compose/config/kuzzlerc.prod
  docker-compose/docker-compose.yml.tpl
  lib/index.js
  lib/node.js
Labels: changelog:new-features

#57 CI setup + fix existing unit tests
  .travis.yml
  README.md
  lib/index.js
  lib/node.js
  lib/redis/manager.js
  lib/redis/state.js
  package-lock.json
  package.json
  sonar-project.properties
  test/lib/index.test.js
  test/lib/node.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/node.mock.js
  test/mocks/redis.mock.js
  test/mocks/stateManager.mock.js
  test/travis-bin/sonar.sh
Labels: changelog:exclude
