Repository kuzzleio/kuzzle-plugin-cluster, pull requests merged in 2018-10, with the labels that each got.

#63 trying to avoid split brains for 2n nodes configurations
  docker-compose/images/kuzzle/Dockerfile
  lib/node.js
  package.json
  test/lib/node.test.js
  test/mocks/redisSateManager.mock.js
Labels: changelog:enhancements

#64 Release 3.2.6
  docker-compose/images/kuzzle/Dockerfile
  lib/node.js
  package-lock.json
  package.json
  test/lib/node.test.js
  test/mocks/redisSateManager.mock.js
Labels: release

#66 fix redis cluster init
  docker-compose/docker-compose.yml.tpl
  docker-compose/redis-cluster-init/Dockerfile
  docker-compose/redis-cluster-init/docker-entrypoint.sh
Labels: changelog:bug-fixes
