Repository kuzzleio/kuzzle-plugin-cluster, pull requests merged in 2019-11, with the labels that each got.

#96 fix error handling on subscription errors
  lib/index.js
  test/lib/index.test.js
Labels: changelog:bug-fixes

#97 Prevent JS Injections
  .eslintrc.json
  lib/index.js
  lib/node.js
  lib/redis/cleanNode.lua
  lib/redis/getState.lua
  lib/redis/manager.js
  lib/redis/suboff.lua
  lib/redis/subon.lua
  manifest.json
  package-lock.json
  package.json
  test/lib/index.test.js
  test/lib/node.test.js
  test/lib/redis/manager.test.js
  test/mocha.opts
  test/mocks/kuzzle.mock.js
  test/mocks/redis.mock.js
  test/mocks/redisSateManager.mock.js
  test/mocks/stateManager.mock.js
  test/mocks/zeromq.mock.js
Labels: changelog:securities

#98 Release 3.2.13
  .eslintrc.json
  lib/index.js
  lib/node.js
  lib/redis/cleanNode.lua
  lib/redis/getState.lua
  lib/redis/manager.js
  lib/redis/suboff.lua
  lib/redis/subon.lua
  manifest.json
  package-lock.json
  package.json
  test/lib/index.test.js
  test/lib/node.test.js
  test/lib/redis/manager.test.js
  test/mocha.opts
  test/mocks/kuzzle.mock.js
  test/mocks/redis.mock.js
  test/mocks/redisSateManager.mock.js
  test/mocks/stateManager.mock.js
  test/mocks/zeromq.mock.js
Labels: release

#99 Prevent JS Injections
  .eslintrc.json
  docker-compose/config/kuzzlerc.dev
  docker-compose/config/kuzzlerc.prod
  docker-compose/config/pm2-dev.json
  docker-compose/docker-compose.yml.tpl
  docker-compose/images/kuzzle/Dockerfile
  lib/index.js
  lib/node.js
  lib/redis/cleanNode.lua
  lib/redis/getState.lua
  lib/redis/manager.js
  lib/redis/suboff.lua
  lib/redis/subon.lua
  package-lock.json
  package.json
  test/lib/index.test.js
  test/lib/node.test.js
  test/lib/redis/manager.test.js
  test/mocha.opts
  test/mocks/kuzzle.mock.js
  test/mocks/redis.mock.js
  test/mocks/redisSateManager.mock.js
  test/mocks/stateManager.mock.js
  test/mocks/zeromq.mock.js
  test/travis-bin/functional-tests.sh
Labels: 4-dev, changelog:securities

#100 Release 4.0.1
  .eslintrc.json
  docker-compose/config/pm2-dev.json
  docker-compose/docker-compose.yml.tpl
  lib/index.js
  lib/node.js
  lib/redis/cleanNode.lua
  lib/redis/getState.lua
  lib/redis/manager.js
  lib/redis/suboff.lua
  lib/redis/subon.lua
  package-lock.json
  package.json
  test/lib/index.test.js
  test/lib/node.test.js
  test/lib/redis/manager.test.js
  test/mocha.opts
  test/mocks/kuzzle.mock.js
  test/mocks/redis.mock.js
  test/mocks/redisSateManager.mock.js
  test/mocks/stateManager.mock.js
  test/mocks/zeromq.mock.js
  test/travis-bin/functional-tests.sh
Labels: release

#101 Correctly apply the NODE_ENV configuration in the dev start script
  docker-compose/build-compose.sh
  docker-compose/docker-compose.yml.tpl
Labels: 3.x, changelog:exclude

#102 Correctly apply the NODE_ENV configuration in the dev start script
  docker-compose/build-compose.sh
  docker-compose/docker-compose.yml.tpl
Labels: 4.x, changelog:exclude
