Repository kuzzleio/kuzzle-plugin-cluster, pull requests merged in 2019-09, with the labels that each got.

#84 Remove the deprecated notifications state
  lib/node.js
  test/lib/node.test.js
Labels: changelog:enhancements

#86 Use the new storageEngine.indexCache
  lib/node.js
  test/lib/node.test.js
  test/mocks/kuzzle.mock.js
Labels: 4-dev, changelog:exclude

#91 Release 4.0.0
  .eslintrc
  Dockerfile
  lib/index.js
  lib/node.js
  package-lock.json
  package.json
  test/lib/index.test.js
  test/lib/node.test.js
  test/mocks/kuzzle.mock.js
Labels: release
